version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Seoul
    reviewers:
      - SidRoberts
    labels:
      - dependencies
