version: '3'
services:
  nginx:
    image: nginx:1-alpine
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/app/
      - ./resources/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    image: sidroberts/php
    volumes:
      - .:/app/
      - ./resources/docker/php.ini:/usr/local/etc/php-fpm.d/zzz-custom.conf
