services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app/:ro
      - ./resources/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    image: sidroberts/php
    volumes:
      - .:/app/
      - ./resources/docker/php.ini:/usr/local/etc/php-fpm.d/zzz-custom.conf:ro
  beanstalkd:
    image: sidroberts/beanstalkd:1.13
  background:
    image: sidroberts/php
    volumes:
      - .:/app/
    command: php /app/bin/centum queue-consume
    restart: always
